export const appRoutes = {
  home: '/',
  catalog: '/catalogo',
  category: '/catalogo/:categorySlug',
  productDetail: '/produto/:productId',
  map: '/mapa',
  calendar: '/calendario',
  school: '/escolinha',
  addProduct: '/cadastrar-produto',
  addEvent: '/cadastrar-evento',
  onboarding: '/boas-vindas',
  admin: '/admin',
  adminSellers: '/admin/vendedores',
  adminProducts: '/admin/produtos',
  adminEvents: '/admin/eventos',
  adminSellerDetail: '/admin/vendedor/:id',
  adminProductDetail: '/admin/produto/:id',
  adminEventDetail: '/admin/evento/:id',
} as const

